all:
	sudo python $(target)

install:
	sudo apt-get install -y python-dev libmysqlclient-dev
	sudo apt-get install -y python python-pip
	sudo apt-get install -y python-numpy
	sudo apt-get install -y mysql-server
	sudo apt-get install -y python-mysqldb
	
clean:
	sudo rm -rf API/*.pyc
	sudo rm -f *.txt

