/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-i2nsf-capability.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_I2NSF_CAPABILITY_H_
#define _IETF_I2NSF_CAPABILITY_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef iicapa__ns
#define iicapa__ns 249337898
#define iicapa__ns_id "urn:ietf:params:xml:ns:yang:ietf-i2nsf-capability"
#define iicapa__ns_uri "urn:ietf:params:xml:ns:yang:ietf-i2nsf-capability"
#endif

#define iicapa_system_event_capa 256876683
#define iicapa_ipv4_geoip 1871509031
#define iicapa_forwarding 1238173057
#define iicapa_range_ipv6_payload_length 1132693264
#define iicapa_drop 414370175
#define iicapa_whitelists 1883693954
#define iicapa_rule_log 912362159
#define iicapa_user_agent 1242907368
#define iicapa_cpu_alarm 727651103
#define iicapa_range_tcp_seq_num 2017234630
#define iicapa_exact_ipv4_fragment_offset 1781980232
#define iicapa_dns_request_flood_action 1678434223
#define iicapa_range_ipv6_hop_limit 1860378356
#define iicapa_pass 833223910
#define iicapa_invoke_signaling 1584205694
#define iicapa_ipv6_traffic_class 1422189984
#define iicapa_exact_ipv4_address 327276219
#define iicapa_exact_ipv4_header_length 476425618
#define iicapa_syn_flood_action 1203647087
#define iicapa_icmp_capa 330440035
#define iicapa_pmrn 578570297
#define iicapa_exact_udp_port_num 1556807868
#define iicapa_sip_flood_action 786302691
#define iicapa_range_udp_total_length 1689149472
#define iicapa_exact_tcp_port_num 566497287
#define iicapa_nsf 1620609679
#define iicapa_action_capabilities 1897613084
#define iicapa_access_violation 567928079
#define iicapa_range_ipv6_address 1637573577
#define iicapa_hardware_alarm 628598332
#define iicapa_event_capabilities 2134940887
#define iicapa_ipv4_tos 619879030
#define iicapa_ipv4_sameip 109404209
#define iicapa_ingress_action_capa 1861461564
#define iicapa_antiddos_capa 2103409698
#define iicapa_url 1560781157
#define iicapa_pmr 54113660
#define iicapa_ipv6_next_header 1379648674
#define iicapa_ips_exception_signature 1103212004
#define iicapa_udp_capa 1945073562
#define iicapa_pmre 48831397
#define iicapa_https_flood_action 354004907
#define iicapa_ipv4_ipopts 583083745
#define iicapa_range_ipv4_header_length 1327458377
#define iicapa_condition 1305639641
#define iicapa_range_ipv6_flow_label 130538749
#define iicapa_configuration_change 480000642
#define iicapa_interface_alarm 1980185781
#define iicapa_tunnel_encapsulation 400213751
#define iicapa_default_action_capa 79711102
#define iicapa_exact_ipv4_total_length 1069753803
#define iicapa_antivirus_capa 1563916042
#define iicapa_detect_mode 1652062949
#define iicapa_exact_udp_total_length 1616986539
#define iicapa_exact_ipv4_ttl 1519314397
#define iicapa_udp_flood_action 981281629
#define iicapa_ipv4_id 1261177528
#define iicapa_tcp_capa 478407059
#define iicapa_exact_ipv6_address 1308014700
#define iicapa_baseline_learn 473147672
#define iicapa_exact_ipv6_flow_label 235892910
#define iicapa_tcp_flags 2105017645
#define iicapa_signature_set 1993065295
#define iicapa_periodic_time 1
#define iicapa_uri 1237918064
#define iicapa_ipv6_capa 1555434717
#define iicapa_exact_tcp_window_size 73038399
#define iicapa_event 1332659655
#define iicapa_log_action_capa 1169487805
#define iicapa_alert 268671234
#define iicapa_range_ipv4_fragment_offset 391794940
#define iicapa_detect 1157973981
#define iicapa_absolute_time 0
#define iicapa_resolution_strategy_capa 1467299116
#define iicapa_session_log 1919273211
#define iicapa_resolution_strategy_capabilities 1090065305
#define iicapa_advanced_nsf_capabilities 1657876965
#define iicapa_default_action_capabilities 1404915488
#define iicapa_range_tcp_window_size 1867122288
#define iicapa_exact_ipv6_payload_length 555681192
#define iicapa_icmp_type 1950250676
#define iicapa_fmr 1662684160
#define iicapa_time_capabilities 2010897230
#define iicapa_mirror 1704418088
#define iicapa_exception_application 580449248
#define iicapa_lmr 1888716461
#define iicapa_egress_action_capa 1621416729
#define iicapa_reject 2072408887
#define iicapa_http_capa 1073253665
#define iicapa_voip_volte_capa 1788683489
#define iicapa_ipv4_capa 1671902436
#define iicapa_memory_alarm 1670602543
#define iicapa_ips_capa 1847283268
#define iicapa_condition_capabilities 1191218041
#define iicapa_exact_tcp_ack_num 1924369419
#define iicapa_range_ipv4_address 257479332
#define iicapa_range_tcp_port_num 1056573702
#define iicapa_exact_ipv6_hop_limit 1958244678
#define iicapa_range_ipv4_total_length 322131663
#define iicapa_range_ipv4_ttl 1141156089
#define iicapa_ipv4_protocol 1717569599
#define iicapa_dns_reply_flood_action 1171373267
#define iicapa_advanced_nsf_capa 760331255
#define iicapa_icmp_flood_action 171275507
#define iicapa_exception_signature 2119803486
#define iicapa_range_tcp_ack_num 1741407135
#define iicapa_exact_tcp_seq_num 45699464
#define iicapa_ipv4_fragment_flags 1796560193
#define iicapa_system_alarm_capa 454154254
#define iicapa_disk_alarm 434463387
#define iicapa_generic_nsf_capabilities 1115329919
#define iicapa_http_flood_action 293195492
#define iicapa_voice_id 1026385330
#define iicapa_redirection 244957141
#define iicapa_range_udp_port_num 1041303362

#ifdef __cplusplus
}
#endif

#endif
