/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ietf-i2nsf-reg-interface.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _IETF_I2NSF_REG_INTERFACE_H_
#define _IETF_I2NSF_REG_INTERFACE_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef iiregi__ns
#define iiregi__ns 13185865
#define iiregi__ns_id "urn:ietf:params:xml:ns:yang:ietf-i2nsf-reg-interface"
#define iiregi__ns_uri "urn:ietf:params:xml:ns:yang:ietf-i2nsf-reg-interface"
#endif

#define iiregi_system_event_capa 256876683
#define iiregi_outbound 1680805655
#define iiregi_processing_peak 272618833
#define iiregi_nsf_access_info 88169171
#define iiregi_inbound_average 1963168386
#define iiregi_outbound_average 231764675
#define iiregi_icmp_capa 330440035
#define iiregi_inbound_peak 1883757266
#define iiregi_nsf_address 1446856187
#define iiregi_action_capabilities 1897613084
#define iiregi_event_capabilities 2134940887
#define iiregi_ingress_action_capa 1861461564
#define iiregi_inbound 1227481211
#define iiregi_antiddos_capa 2103409698
#define iiregi_udp_capa 1945073562
#define iiregi_antivirus_capa 1563916042
#define iiregi_i2nsf_capability 406826155
#define iiregi_nsf_port_address 1397589716
#define iiregi_tcp_capa 478407059
#define iiregi_nsf_capability_info 169357039
#define iiregi_periodic_time 1
#define iiregi_i2nsf_nsf_capability_query 467807320
#define iiregi_nsf_performance_capability 1062989097
#define iiregi_ipv6_capa 1555434717
#define iiregi_log_action_capa 1169487805
#define iiregi_query_i2nsf_capability_info 263238701
#define iiregi_outbound_peak 1132864929
#define iiregi_absolute_time 0
#define iiregi_resolution_strategy_capabilities 1090065305
#define iiregi_advanced_nsf_capabilities 1657876965
#define iiregi_default_action_capabilities 1404915488
#define iiregi_i2nsf_nsf_registrations 549976631
#define iiregi_time_capabilities 2010897230
#define iiregi_nsf_instance_name 807810263
#define iiregi_egress_action_capa 1621416729
#define iiregi_http_capa 1073253665
#define iiregi_bandwidth 82191353
#define iiregi_voip_volte_capa 1788683489
#define iiregi_nsf_name 59165401
#define iiregi_ipv4_capa 1671902436
#define iiregi_ips_capa 1847283268
#define iiregi_processing_average 1279811073
#define iiregi_condition_capabilities 1191218041
#define iiregi_processing 550522802
#define iiregi_system_alarm_capa 454154254
#define iiregi_generic_nsf_capabilities 1115329919
#define iiregi_i2nsf_nsf_capability_registration 831838589

#ifdef __cplusplus
}
#endif

#endif
