%%
%% BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
%% This file has been auto-generated by the confdc compiler.
%% Source: users.fxs
%% BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
%%



-define(users__ns, 806785777).
-define(users__ns_id, 'http://tail-f.com/ns/example/users').
-define(users__ns_uri, 'http://tail-f.com/ns/example/users').
-define(users_oper, 1).
-define(users_role, 1297556411).
-define(users_users, 987101583).
-define(users_name, 1998270519).
-define(users_admin, 0).
-define(users_password, 880727685).
-define(users_user, 1529217067).
-define(users__callpointid_simple_aaa, 'simple_aaa').
