#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: dhcpd.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module dhcpd.yang


class ns(object):
    hash = 1946994318

    id = "http://tail-f.com/ns/example/dhcpd"

    uri = "http://tail-f.com/ns/example/dhcpd"

    prefix = "dhcpd"

    dhcpd_kern = 0
    dhcpd_kern_ = "kern"
    dhcpd_range = 28853268
    dhcpd_range_ = "range"
    dhcpd_local7 = 2
    dhcpd_local7_ = "local7"
    dhcpd_log_facility = 2049412155
    dhcpd_log_facility_ = "log-facility"
    dhcpd_routers = 1226429584
    dhcpd_routers_ = "routers"
    dhcpd_shared_networks = 511577759
    dhcpd_shared_networks_ = "shared-networks"
    dhcpd_hi_addr = 1217286238
    dhcpd_hi_addr_ = "hi-addr"
    dhcpd_shared_network = 256078062
    dhcpd_shared_network_ = "shared-network"
    dhcpd_mail = 1
    dhcpd_mail_ = "mail"
    dhcpd_low_addr = 2122895953
    dhcpd_low_addr_ = "low-addr"
    dhcpd_dhcp = 990408299
    dhcpd_dhcp_ = "dhcp"
    dhcpd_net = 872020178
    dhcpd_net_ = "net"
    dhcpd_mask = 1167181041
    dhcpd_mask_ = "mask"
    dhcpd_name = 1998270519
    dhcpd_name_ = "name"
    dhcpd_dynamic_bootp = 29929361
    dhcpd_dynamic_bootp_ = "dynamic-bootp"
    dhcpd_subnets = 1650094351
    dhcpd_subnets_ = "subnets"
    dhcpd_subnet = 1544472008
    dhcpd_subnet_ = "subnet"
    dhcpd_default_lease_time = 1186076854
    dhcpd_default_lease_time_ = "default-lease-time"
    dhcpd_max_lease_time = 1794251668
    dhcpd_max_lease_time_ = "max-lease-time"
