#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ietf-i2nsf-registration-interface.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-i2nsf-registration-interface.yang


class ns(object):
    hash = 1685339224

    id = "urn:ietf:params:xml:ns:yang:ietf-i2nsf-registration-interface"

    uri = "urn:ietf:params:xml:ns:yang:ietf-i2nsf-registration-interface"

    prefix = "i2nsfri"

    i2nsfri_disk = 334675513
    i2nsfri_disk_ = "disk"
    i2nsfri_nsf_capability_update = 1961631582
    i2nsfri_nsf_capability_update_ = "nsf-capability-update"
    i2nsfri_event_capabilities = 2134940887
    i2nsfri_event_capabilities_ = "event-capabilities"
    i2nsfri_clock_speed = 188680799
    i2nsfri_clock_speed_ = "clock-speed"
    i2nsfri_outbound = 1680805655
    i2nsfri_outbound_ = "outbound"
    i2nsfri_cores = 400049979
    i2nsfri_cores_ = "cores"
    i2nsfri_cpu = 1825182739
    i2nsfri_cpu_ = "cpu"
    i2nsfri_ingress_action_capability = 1352320416
    i2nsfri_ingress_action_capability_ = "ingress-action-capability"
    i2nsfri_model = 1068274359
    i2nsfri_model_ = "model"
    i2nsfri_context_capabilities = 1547473613
    i2nsfri_context_capabilities_ = "context-capabilities"
    i2nsfri_dccp_capability = 1356188887
    i2nsfri_dccp_capability_ = "dccp-capability"
    i2nsfri_ethernet_capability = 2117464875
    i2nsfri_ethernet_capability_ = "ethernet-capability"
    i2nsfri_memory = 1156186237
    i2nsfri_memory_ = "memory"
    i2nsfri_inbound = 1227481211
    i2nsfri_inbound_ = "inbound"
    i2nsfri_udp_capability = 1671949129
    i2nsfri_udp_capability_ = "udp-capability"
    i2nsfri_anti_virus_capability = 326334402
    i2nsfri_anti_virus_capability_ = "anti-virus-capability"
    i2nsfri_tcp_capability = 1888613575
    i2nsfri_tcp_capability_ = "tcp-capability"
    i2nsfri_device_type_capabilities = 351597291
    i2nsfri_device_type_capabilities_ = "device-type-capabilities"
    i2nsfri_bandwidth = 82191353
    i2nsfri_bandwidth_ = "bandwidth"
    i2nsfri_port = 10387472
    i2nsfri_port_ = "port"
    i2nsfri_log_action_capability = 819941140
    i2nsfri_log_action_capability_ = "log-action-capability"
    i2nsfri_nsf_specification = 1875969998
    i2nsfri_nsf_specification_ = "nsf-specification"
    i2nsfri_ips_capability = 152523560
    i2nsfri_ips_capability_ = "ips-capability"
    i2nsfri_nsf_name = 59165401
    i2nsfri_nsf_name_ = "nsf-name"
    i2nsfri_sctp_capability = 1448939530
    i2nsfri_sctp_capability_ = "sctp-capability"
    i2nsfri_directional_capabilities = 2095740578
    i2nsfri_directional_capabilities_ = "directional-capabilities"
    i2nsfri_version = 1714291735
    i2nsfri_version_ = "version"
    i2nsfri_geographic_capabilities = 1886418677
    i2nsfri_geographic_capabilities_ = "geographic-capabilities"
    i2nsfri_condition_capabilities = 1191218041
    i2nsfri_condition_capabilities_ = "condition-capabilities"
    i2nsfri_RESTCONF = 1
    i2nsfri_RESTCONF_ = "RESTCONF"
    i2nsfri_threads = 913602357
    i2nsfri_threads_ = "threads"
    i2nsfri_nsf_access_info = 88169171
    i2nsfri_nsf_access_info_ = "nsf-access-info"
    i2nsfri_ipv4_capability = 318504331
    i2nsfri_ipv4_capability_ = "ipv4-capability"
    i2nsfri_capacity = 191070892
    i2nsfri_capacity_ = "capacity"
    i2nsfri_system_event_capability = 1811402511
    i2nsfri_system_event_capability_ = "system-event-capability"
    i2nsfri_system_alarm_capability = 430599408
    i2nsfri_system_alarm_capability_ = "system-alarm-capability"
    i2nsfri_user_condition_capabilities = 602821350
    i2nsfri_user_condition_capabilities_ = "user-condition-capabilities"
    i2nsfri_speed = 1423237997
    i2nsfri_speed_ = "speed"
    i2nsfri_NETCONF = 0
    i2nsfri_NETCONF_ = "NETCONF"
    i2nsfri_advanced_nsf_capabilities = 1657876965
    i2nsfri_advanced_nsf_capabilities_ = "advanced-nsf-capabilities"
    i2nsfri_resolution_strategy_capabilities = 1090065305
    i2nsfri_resolution_strategy_capabilities_ = "resolution-strategy-capabilities"
    i2nsfri_voip_vocn_filtering_capability = 518277237
    i2nsfri_voip_vocn_filtering_capability_ = "voip-vocn-filtering-capability"
    i2nsfri_management_protocol = 896882527
    i2nsfri_management_protocol_ = "management-protocol"
    i2nsfri_application_filter_capabilities = 1359026577
    i2nsfri_application_filter_capabilities_ = "application-filter-capabilities"
    i2nsfri_egress_action_capability = 1907679921
    i2nsfri_egress_action_capability_ = "egress-action-capability"
    i2nsfri_ipv6_capability = 1027943469
    i2nsfri_ipv6_capability_ = "ipv6-capability"
    i2nsfri_default_action_capabilities = 1404915488
    i2nsfri_default_action_capabilities_ = "default-action-capabilities"
    i2nsfri_generic_nsf_capabilities = 1115329919
    i2nsfri_generic_nsf_capabilities_ = "generic-nsf-capabilities"
    i2nsfri_nsf = 1620609679
    i2nsfri_nsf_ = "nsf"
    i2nsfri_ip = 1643785435
    i2nsfri_ip_ = "ip"
    i2nsfri_icmpv6_capability = 1305583348
    i2nsfri_icmpv6_capability_ = "icmpv6-capability"
    i2nsfri_query_nsf_capability = 1336944259
    i2nsfri_query_nsf_capability_ = "query-nsf-capability"
    i2nsfri_anti_ddos_capability = 129529422
    i2nsfri_anti_ddos_capability_ = "anti-ddos-capability"
    i2nsfri_action_capabilities = 1897613084
    i2nsfri_action_capabilities_ = "action-capabilities"
    i2nsfri_nsf_capability_registration = 1502099184
    i2nsfri_nsf_capability_registration_ = "nsf-capability-registration"
    i2nsfri_url_filtering_capability = 1851865662
    i2nsfri_url_filtering_capability_ = "url-filtering-capability"
    i2nsfri_icmpv4_capability = 2146727404
    i2nsfri_icmpv4_capability_ = "icmpv4-capability"
    i2nsfri_time_capabilities = 2010897230
    i2nsfri_time_capabilities_ = "time-capabilities"
    actionpoint_registration = "registration"
