FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y upgrade 
RUN apt-get install -y python3-setuptools python3-dev python3-pip \
    libssl-dev git net-tools aptitude build-essential software-properties-common \
    ansible curl iptables iputils-ping sudo

ADD ./mininet /home/ubuntu

WORKDIR /home/ubuntu
RUN chmod 777 -R /home/ubuntu
RUN git clone https://github.com/containernet/containernet.git
WORKDIR /home/ubuntu/containernet/ansible
RUN ansible-playbook -i "localhost," -c local --skip-tags "notindocker" install.yml
WORKDIR /home/ubuntu/containernet
RUN make develop

EXPOSE 55564

# Hotfix: https://github.com/pytest-dev/pytest/issues/4770
RUN pip3 install "more-itertools<=5.0.0"

# tell containernet that it runs in a container
ENV CONTAINERNET_NESTED 1

WORKDIR /home/ubuntu
# Important: This entrypoint is required to start the OVS service
ENTRYPOINT ["containernet/util/docker/entrypoint.sh"]
CMD ["python3", "mininet_server.py"]
